/**
 * Build-time sprite library codegen.
 *
 * The game runtime has no filesystem access, so the icon collection cannot be
 * scanned while the mod runs. Instead this script walks `assets/icons/` and
 * writes a static manifest that the UI imports.
 *
 * Run via:  deno task build:sprites
 * The output is committed so `deno check` works without running the task.
 */
import { walk } from "jsr:@std/fs@1/walk";

const ROOT = new URL("..", import.meta.url);
const ICONS = new URL("assets/icons/", ROOT);
const OUT = new URL("src/generated/sprite-library.ts", ROOT);

/** Split "icon-alien-2x2.png" → { name: "icon-alien", size: "2x2" }. */
function parseFile(file: string): { name: string; size: string } | null {
    const m = /^(.*?)-(\d+x\d+)\.png$/.exec(file);
    if (!m) return null;
    return { name: m[1], size: m[2] };
}

/** Sort "3x3" > "2x2" so the default path uses the highest-resolution asset. */
function sizeRank(size: string): number {
    const [w, h] = size.split("x").map(Number);
    return (Number.isFinite(w) ? w : 0) * 1000 + (Number.isFinite(h) ? h : 0);
}

interface Entry {
    name: string;
    /** size → mod-root-relative path. */
    paths: Record<string, string>;
    /** Pixel dimensions of the previewed PNG, filled in below. */
    previewW: number;
    previewH: number;
}

/**
 * Inline the PNG as a data URL so the panel can show the real art.
 *
 * The game runtime has no filesystem access, so the bytes have to be baked in at
 * build time — there is no way to read them back while the mod runs. Every icon
 * is a 16×16 cell, so the whole set costs ~30 KB of base64 and gives an exact
 * preview rather than a stand-in.
 */
async function previewDataUrl(file: URL, bytes?: Uint8Array): Promise<string> {
    const data = bytes ?? await Deno.readFile(file);
    let bin = "";
    for (const b of data) bin += String.fromCharCode(b);
    return `data:image/png;base64,${btoa(bin)}`;
}

/** PNG dimensions from the IHDR chunk (bytes 16..24 of the file). */
function pngSize(bytes: Uint8Array): { w: number; h: number } {
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return { w: view.getUint32(16), h: view.getUint32(20) };
}

const entries = new Map<string, Entry>();
let skipped = 0;

for await (const item of walk(ICONS, { exts: [".png"] })) {
    if (!item.isFile) continue;
    const file = item.name;
    const parsed = parseFile(file);
    if (!parsed) {
        skipped++;
        continue;
    }
    const rel = `assets/icons/${file}`;
    const prev = entries.get(parsed.name);
    if (prev) {
        prev.paths[parsed.size] = rel;
    } else {
        entries.set(parsed.name, { name: parsed.name, paths: { [parsed.size]: rel } });
    }
}

const list = [...entries.values()].sort((a, b) => a.name.localeCompare(b.name));

// Fill in the previewed PNG's real pixel dimensions and inline it as a data URL.
// (previewDataUrl is async, so this must happen before the sync template build —
// JSON.stringify on a Promise would silently emit `{}`.)
for (const e of list) {
    const sizes = Object.keys(e.paths).sort((a, b) => sizeRank(b) - sizeRank(a));
    const file = new URL(e.paths[sizes[0]], ROOT);
    const bytes = await Deno.readFile(file);
    const { w, h } = pngSize(bytes);
    e.previewW = w;
    e.previewH = h;
    e.preview = await previewDataUrl(file, bytes);
}

const body = list
    .map((e) => {
        const sizes = Object.keys(e.paths).sort((a, b) => sizeRank(b) - sizeRank(a));
        const path = e.paths[sizes[0]];
        return `    { name: ${JSON.stringify(e.name)}, path: ${JSON.stringify(path)}, sizes: ${
            JSON.stringify(sizes)
        }, preview: ${
            JSON.stringify(e.preview)
        }, previewW: ${e.previewW}, previewH: ${e.previewH} },`;
    })
    .join("\n");

const file = `/**
 * AUTO-GENERATED by tools/gen-sprite-library.ts — do not edit by hand.
 * Run \`deno task build:sprites\` after adding files to assets/icons/.
 *
 * Every entry is a real PNG shipped inside this mod, so a sprite can be
 * registered with sprites.loadFromMod(<graphicsKey>, <path>) without the user
 * having to know the on-disk filename. \`path\` is the highest-resolution
 * variant; \`sizes\` lists the cell sizes that exist for this icon.
 */
export interface LibraryIcon {
    /** Base name, e.g. "icon-alien" (from icon-alien-2x2.png). */
    name: string;
    /** Mod-root-relative path passed straight to loadFromMod (largest variant). */
    path: string;
    /** Available cell sizes, largest first, e.g. ["3x3", "2x2", "1x1"]. */
    sizes: string[];
    /**
     * The PNG inlined as a data URL, so the panel can render the real art. The
     * runtime has no filesystem access, so this is the only way to see an icon.
     */
    preview: string;
    /** Pixel size of the previewed PNG (16x16 for a 1x1 icon). */
    previewW: number;
    previewH: number;
}

export const LIBRARY_ICONS: LibraryIcon[] = [
${body}
];

/** Case-insensitive substring search used by the sprite picker. */
export function searchLibraryIcons(query: string): LibraryIcon[] {
    const q = query.trim().toLowerCase();
    if (!q) return LIBRARY_ICONS;
    return LIBRARY_ICONS.filter((i) => i.name.toLowerCase().includes(q));
}
`;

await Deno.mkdir(new URL("src/generated/", ROOT), { recursive: true });
await Deno.writeTextFile(OUT, file);
console.log(
    `sprite-library: ${list.length} icons (${skipped} files skipped) → ${
        new URL("src/generated/sprite-library.ts", ROOT).pathname
    }`,
);
