/** AUTO-GENERATED by tools/generate-catalogue.mjs — do not edit */
import type { CatalogueCategory, CatalogueItem } from "@sandmd/catalogue";

export const ICON_CATEGORIES: CatalogueCategory[] = [
  {
    "id": "button__",
    "label": "Btton__"
  },
  {
    "id": "counter_1",
    "label": "Cunter_1"
  },
  {
    "id": "counter__",
    "label": "Cunter__"
  },
  {
    "id": "display_2",
    "label": "Dsplay_2"
  },
  {
    "id": "display_3",
    "label": "Dsplay_3"
  },
  {
    "id": "display__",
    "label": "Dsplay__"
  },
  {
    "id": "dpad__",
    "label": "Dad__"
  },
  {
    "id": "gauge_1",
    "label": "Guge_1"
  },
  {
    "id": "gauge__",
    "label": "Guge__"
  },
  {
    "id": "led__",
    "label": "Ld__"
  },
  {
    "id": "minus__",
    "label": "Mnus__"
  },
  {
    "id": "plus__",
    "label": "Pus__"
  },
  {
    "id": "pulse__",
    "label": "Plse__"
  },
  {
    "id": "range_1",
    "label": "Rnge_1"
  },
  {
    "id": "range__",
    "label": "Rnge__"
  },
  {
    "id": "selector_1",
    "label": "Slector_1"
  },
  {
    "id": "selector__",
    "label": "Slector__"
  },
  {
    "id": "text_1",
    "label": "Txt_1"
  },
  {
    "id": "text__",
    "label": "Txt__"
  },
  {
    "id": "toggle__",
    "label": "Tggle__"
  }
];

export const ICON_ITEMS: CatalogueItem[] = [
  {
    "id": "icons",
    "label": "Icons",
    "category": "glyphs",
    "width": 16,
    "height": 16,
    "file": "assets/char-A-1x1.png",
    "align": "wall",
    "description": "Decorative. No collision."
  },
  {
    "id": "button",
    "label": "Button",
    "category": "button__",
    "width": 16,
    "height": 16,
    "file": "assets/button.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "counter",
    "label": "Counter",
    "category": "counter__",
    "width": 16,
    "height": 16,
    "file": "assets/counter.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "counter-2x1",
    "label": "Counter 2x1",
    "category": "counter__",
    "width": 32,
    "height": 16,
    "file": "assets/counter-2x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "counter-3x1",
    "label": "Counter 3x1",
    "category": "counter__",
    "width": 48,
    "height": 16,
    "file": "assets/counter-3x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "counter-4x1",
    "label": "Counter 4x1",
    "category": "counter__",
    "width": 64,
    "height": 16,
    "file": "assets/counter-4x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "counter-5x1",
    "label": "Counter 5x1",
    "category": "counter__",
    "width": 80,
    "height": 16,
    "file": "assets/counter-5x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "counter-1x1",
    "label": "Counter 1x1",
    "category": "counter_1",
    "width": 16,
    "height": 16,
    "file": "assets/counter-1x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "display",
    "label": "Display",
    "category": "display__",
    "width": 16,
    "height": 16,
    "file": "assets/display.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "display-2x1",
    "label": "Display 2x1",
    "category": "display__",
    "width": 32,
    "height": 16,
    "file": "assets/display-2x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "display-3x1",
    "label": "Display 3x1",
    "category": "display__",
    "width": 48,
    "height": 16,
    "file": "assets/display-3x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "display-4x1",
    "label": "Display 4x1",
    "category": "display__",
    "width": 64,
    "height": 16,
    "file": "assets/display-4x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "display-5x1",
    "label": "Display 5x1",
    "category": "display__",
    "width": 80,
    "height": 16,
    "file": "assets/display-5x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "display-2x2",
    "label": "Display 2x2",
    "category": "display_2",
    "width": 32,
    "height": 32,
    "file": "assets/display-2x2.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "display-3x3",
    "label": "Display 3x3",
    "category": "display_3",
    "width": 48,
    "height": 48,
    "file": "assets/display-3x3.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "dpad",
    "label": "Dpad",
    "category": "dpad__",
    "width": 16,
    "height": 16,
    "file": "assets/dpad.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "gauge",
    "label": "Gauge",
    "category": "gauge__",
    "width": 16,
    "height": 16,
    "file": "assets/gauge.png",
    "align": "wall",
    "description": "Decorative. No collision."
  },
  {
    "id": "gauge-2x1",
    "label": "Gauge 2x1",
    "category": "gauge__",
    "width": 32,
    "height": 16,
    "file": "assets/gauge-2x1.png",
    "align": "wall",
    "description": "Decorative. No collision."
  },
  {
    "id": "gauge-3x1",
    "label": "Gauge 3x1",
    "category": "gauge__",
    "width": 48,
    "height": 16,
    "file": "assets/gauge-3x1.png",
    "align": "wall",
    "description": "Decorative. No collision."
  },
  {
    "id": "gauge-4x1",
    "label": "Gauge 4x1",
    "category": "gauge__",
    "width": 64,
    "height": 16,
    "file": "assets/gauge-4x1.png",
    "align": "wall",
    "description": "Decorative. No collision."
  },
  {
    "id": "gauge-5x1",
    "label": "Gauge 5x1",
    "category": "gauge__",
    "width": 80,
    "height": 16,
    "file": "assets/gauge-5x1.png",
    "align": "wall",
    "description": "Decorative. No collision."
  },
  {
    "id": "gauge-1x1",
    "label": "Gauge 1x1",
    "category": "gauge_1",
    "width": 16,
    "height": 16,
    "file": "assets/gauge-1x1.png",
    "align": "wall",
    "description": "Decorative. No collision."
  },
  {
    "id": "led-off",
    "label": "Led Off",
    "category": "led__",
    "width": 16,
    "height": 16,
    "file": "assets/led-off.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "led-on",
    "label": "Led On",
    "category": "led__",
    "width": 16,
    "height": 16,
    "file": "assets/led-on.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "minus",
    "label": "Minus",
    "category": "minus__",
    "width": 16,
    "height": 16,
    "file": "assets/minus.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "plus",
    "label": "Plus",
    "category": "plus__",
    "width": 16,
    "height": 16,
    "file": "assets/plus.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "pulse",
    "label": "Pulse",
    "category": "pulse__",
    "width": 16,
    "height": 16,
    "file": "assets/pulse.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "range",
    "label": "Range",
    "category": "range__",
    "width": 16,
    "height": 16,
    "file": "assets/range.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "range-2x1",
    "label": "Range 2x1",
    "category": "range__",
    "width": 32,
    "height": 16,
    "file": "assets/range-2x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "range-3x1",
    "label": "Range 3x1",
    "category": "range__",
    "width": 48,
    "height": 16,
    "file": "assets/range-3x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "range-4x1",
    "label": "Range 4x1",
    "category": "range__",
    "width": 64,
    "height": 16,
    "file": "assets/range-4x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "range-5x1",
    "label": "Range 5x1",
    "category": "range__",
    "width": 80,
    "height": 16,
    "file": "assets/range-5x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "range-1x1",
    "label": "Range 1x1",
    "category": "range_1",
    "width": 16,
    "height": 16,
    "file": "assets/range-1x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "selector",
    "label": "Selector",
    "category": "selector__",
    "width": 16,
    "height": 16,
    "file": "assets/selector.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "selector-2x1",
    "label": "Selector 2x1",
    "category": "selector__",
    "width": 32,
    "height": 16,
    "file": "assets/selector-2x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "selector-3x1",
    "label": "Selector 3x1",
    "category": "selector__",
    "width": 48,
    "height": 16,
    "file": "assets/selector-3x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "selector-4x1",
    "label": "Selector 4x1",
    "category": "selector__",
    "width": 64,
    "height": 16,
    "file": "assets/selector-4x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "selector-5x1",
    "label": "Selector 5x1",
    "category": "selector__",
    "width": 80,
    "height": 16,
    "file": "assets/selector-5x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "selector-1x1",
    "label": "Selector 1x1",
    "category": "selector_1",
    "width": 16,
    "height": 16,
    "file": "assets/selector-1x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "text",
    "label": "Text",
    "category": "text__",
    "width": 16,
    "height": 16,
    "file": "assets/text.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "text-2x1",
    "label": "Text 2x1",
    "category": "text__",
    "width": 32,
    "height": 16,
    "file": "assets/text-2x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "text-3x1",
    "label": "Text 3x1",
    "category": "text__",
    "width": 48,
    "height": 16,
    "file": "assets/text-3x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "text-4x1",
    "label": "Text 4x1",
    "category": "text__",
    "width": 64,
    "height": 16,
    "file": "assets/text-4x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "text-5x1",
    "label": "Text 5x1",
    "category": "text__",
    "width": 80,
    "height": 16,
    "file": "assets/text-5x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "text-1x1",
    "label": "Text 1x1",
    "category": "text_1",
    "width": 16,
    "height": 16,
    "file": "assets/text-1x1.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "toggle-off",
    "label": "Toggle Off",
    "category": "toggle__",
    "width": 16,
    "height": 16,
    "file": "assets/toggle-off.png",
    "align": "floor",
    "description": "Decorative. No collision."
  },
  {
    "id": "toggle-on",
    "label": "Toggle On",
    "category": "toggle__",
    "width": 16,
    "height": 16,
    "file": "assets/toggle-on.png",
    "align": "floor",
    "description": "Decorative. No collision."
  }
];

export const ICON_FILES: { id: string; file: string }[] = [
  {
    "id": "icons",
    "file": "assets/char-A-1x1.png"
  },
  {
    "id": "button",
    "file": "assets/button.png"
  },
  {
    "id": "counter",
    "file": "assets/counter.png"
  },
  {
    "id": "counter-2x1",
    "file": "assets/counter-2x1.png"
  },
  {
    "id": "counter-3x1",
    "file": "assets/counter-3x1.png"
  },
  {
    "id": "counter-4x1",
    "file": "assets/counter-4x1.png"
  },
  {
    "id": "counter-5x1",
    "file": "assets/counter-5x1.png"
  },
  {
    "id": "counter-1x1",
    "file": "assets/counter-1x1.png"
  },
  {
    "id": "display",
    "file": "assets/display.png"
  },
  {
    "id": "display-2x1",
    "file": "assets/display-2x1.png"
  },
  {
    "id": "display-3x1",
    "file": "assets/display-3x1.png"
  },
  {
    "id": "display-4x1",
    "file": "assets/display-4x1.png"
  },
  {
    "id": "display-5x1",
    "file": "assets/display-5x1.png"
  },
  {
    "id": "display-2x2",
    "file": "assets/display-2x2.png"
  },
  {
    "id": "display-3x3",
    "file": "assets/display-3x3.png"
  },
  {
    "id": "dpad",
    "file": "assets/dpad.png"
  },
  {
    "id": "gauge",
    "file": "assets/gauge.png"
  },
  {
    "id": "gauge-2x1",
    "file": "assets/gauge-2x1.png"
  },
  {
    "id": "gauge-3x1",
    "file": "assets/gauge-3x1.png"
  },
  {
    "id": "gauge-4x1",
    "file": "assets/gauge-4x1.png"
  },
  {
    "id": "gauge-5x1",
    "file": "assets/gauge-5x1.png"
  },
  {
    "id": "gauge-1x1",
    "file": "assets/gauge-1x1.png"
  },
  {
    "id": "led-off",
    "file": "assets/led-off.png"
  },
  {
    "id": "led-on",
    "file": "assets/led-on.png"
  },
  {
    "id": "minus",
    "file": "assets/minus.png"
  },
  {
    "id": "plus",
    "file": "assets/plus.png"
  },
  {
    "id": "pulse",
    "file": "assets/pulse.png"
  },
  {
    "id": "range",
    "file": "assets/range.png"
  },
  {
    "id": "range-2x1",
    "file": "assets/range-2x1.png"
  },
  {
    "id": "range-3x1",
    "file": "assets/range-3x1.png"
  },
  {
    "id": "range-4x1",
    "file": "assets/range-4x1.png"
  },
  {
    "id": "range-5x1",
    "file": "assets/range-5x1.png"
  },
  {
    "id": "range-1x1",
    "file": "assets/range-1x1.png"
  },
  {
    "id": "selector",
    "file": "assets/selector.png"
  },
  {
    "id": "selector-2x1",
    "file": "assets/selector-2x1.png"
  },
  {
    "id": "selector-3x1",
    "file": "assets/selector-3x1.png"
  },
  {
    "id": "selector-4x1",
    "file": "assets/selector-4x1.png"
  },
  {
    "id": "selector-5x1",
    "file": "assets/selector-5x1.png"
  },
  {
    "id": "selector-1x1",
    "file": "assets/selector-1x1.png"
  },
  {
    "id": "text",
    "file": "assets/text.png"
  },
  {
    "id": "text-2x1",
    "file": "assets/text-2x1.png"
  },
  {
    "id": "text-3x1",
    "file": "assets/text-3x1.png"
  },
  {
    "id": "text-4x1",
    "file": "assets/text-4x1.png"
  },
  {
    "id": "text-5x1",
    "file": "assets/text-5x1.png"
  },
  {
    "id": "text-1x1",
    "file": "assets/text-1x1.png"
  },
  {
    "id": "toggle-off",
    "file": "assets/toggle-off.png"
  },
  {
    "id": "toggle-on",
    "file": "assets/toggle-on.png"
  }
];
