/** AUTO-GENERATED by tools/generate-catalogue.mjs — do not edit */
import type { CatalogueCategory, CatalogueItem } from "@sandmd/catalogue";

export const ICON_CATEGORIES: CatalogueCategory[] = [];

export const ICON_ITEMS: CatalogueItem[] = [
  {
    "id": "icons",
    "label": "Icons",
    "category": "glyphs",
    "width": 16,
    "height": 16,
    "file": "assets/char-A-1x1.png",
    "align": "wall",
    "description": "Decorative. No collision."
  }
];

export const ICON_FILES: { id: string; file: string }[] = [
  {
    "id": "icons",
    "file": "assets/char-A-1x1.png"
  }
];
