/** Shared inline styles for the overlay panel. */
export const COLORS = {
    bg: "rgba(15, 23, 42, 0.92)",
    bgSoft: "rgba(30, 41, 59, 0.9)",
    border: "rgba(148, 163, 184, 0.25)",
    text: "#e2e8f0",
    dim: "#94a3b8",
    good: "#4ade80",
    danger: "#f87171",
    accent: "#38bdf8",
    btn: "rgba(51, 65, 85, 0.9)",
    btnHover: "rgba(71, 85, 105, 0.95)",
    btnPrimary: "rgba(14, 165, 233, 0.85)",
};

export const styles: Record<string, Record<string, string | number>> = {
    root: {
        position: "fixed",
        zIndex: 9000,
        width: 360,
        maxHeight: "80vh",
        display: "flex",
        flexDirection: "column",
        background: COLORS.bg,
        border: `1px solid ${COLORS.border}`,
        borderRadius: 10,
        boxShadow: "0 12px 40px rgba(0,0,0,0.45)",
        color: COLORS.text,
        fontFamily: "system-ui, -apple-system, Segoe UI, sans-serif",
        fontSize: 13,
        overflow: "hidden",
        userSelect: "none",
    },
    rootMini: {
        position: "fixed",
        zIndex: 9000,
        width: 220,
        background: COLORS.bg,
        border: `1px solid ${COLORS.border}`,
        borderRadius: 8,
        boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
        color: COLORS.text,
        fontFamily: "system-ui, -apple-system, Segoe UI, sans-serif",
        fontSize: 12,
        overflow: "hidden",
        userSelect: "none",
    },
    header: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: "8px 10px",
        background: COLORS.bgSoft,
        borderBottom: `1px solid ${COLORS.border}`,
        flexShrink: 0,
    },
    dragHandle: {
        flex: 1,
        minWidth: 0,
    },
    title: {
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 0.2,
    },
    button: {
        background: COLORS.btn,
        border: "none",
        color: COLORS.text,
        borderRadius: 5,
        padding: "4px 8px",
        cursor: "pointer",
        fontSize: 12,
        fontWeight: 600,
    },
    buttonPrimary: {
        background: COLORS.btnPrimary,
        border: "none",
        color: "#fff",
        borderRadius: 5,
        padding: "4px 8px",
        cursor: "pointer",
        fontSize: 12,
        fontWeight: 600,
    },
    buttonDisabled: {
        background: COLORS.btn,
        border: "none",
        color: COLORS.dim,
        borderRadius: 5,
        padding: "4px 8px",
        cursor: "default",
        fontSize: 12,
        opacity: 0.6,
    },
    tabs: {
        display: "flex",
        gap: 2,
        padding: "6px 8px 0",
        flexShrink: 0,
        borderBottom: `1px solid ${COLORS.border}`,
    },
    tab: {
        background: "transparent",
        border: "none",
        color: COLORS.dim,
        padding: "6px 10px",
        cursor: "pointer",
        fontSize: 12,
        fontWeight: 600,
        borderBottom: "2px solid transparent",
    },
    tabActive: {
        background: "transparent",
        border: "none",
        color: COLORS.text,
        padding: "6px 10px",
        cursor: "pointer",
        fontSize: 12,
        fontWeight: 700,
        borderBottom: `2px solid ${COLORS.accent}`,
    },
    body: {
        flex: 1,
        overflowY: "auto",
        padding: "10px 12px",
        minHeight: 120,
    },
    footer: {
        padding: "6px 10px",
        borderTop: `1px solid ${COLORS.border}`,
        color: COLORS.dim,
        fontSize: 10,
        display: "flex",
        justifyContent: "space-between",
        flexShrink: 0,
    },
    card: {
        background: COLORS.bgSoft,
        borderRadius: 8,
        padding: "10px 12px",
        marginBottom: 8,
        borderLeft: "3px solid #94a3b8",
    },
    cardTitle: {
        fontWeight: 700,
        fontSize: 12,
        marginBottom: 4,
        color: COLORS.dim,
        textTransform: "uppercase",
        letterSpacing: 0.4,
    },
    cardTotal: {
        fontSize: 22,
        fontWeight: 800,
        fontVariantNumeric: "tabular-nums",
        lineHeight: 1.15,
    },
    cardDelta: {
        fontSize: 11,
        fontWeight: 600,
        fontVariantNumeric: "tabular-nums",
        marginLeft: 8,
    },
    row: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        padding: "4px 0",
        borderBottom: `1px solid rgba(148,163,184,0.08)`,
    },
    rowLabel: {
        flex: 1,
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    rowCount: {
        fontWeight: 700,
        fontVariantNumeric: "tabular-nums",
        minWidth: 48,
        textAlign: "right",
    },
    barTrack: {
        height: 4,
        borderRadius: 2,
        background: "rgba(148,163,184,0.15)",
        flex: 1,
        maxWidth: 80,
        overflow: "hidden",
    },
    barFill: {
        height: "100%",
        borderRadius: 2,
    },
    miniBody: {
        padding: "6px 8px 8px",
        display: "flex",
        flexDirection: "column",
        gap: 4,
    },
    miniCard: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: "4px 6px",
        background: COLORS.bgSoft,
        borderRadius: 5,
        borderLeft: "3px solid #94a3b8",
    },
    miniCardTitle: {
        flex: 1,
        fontSize: 11,
        color: COLORS.dim,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    miniCardSum: {
        fontWeight: 800,
        fontVariantNumeric: "tabular-nums",
        fontSize: 13,
    },
    sectionTitle: {
        fontWeight: 700,
        fontSize: 11,
        color: COLORS.dim,
        textTransform: "uppercase",
        letterSpacing: 0.4,
        margin: "8px 0 4px",
    },
    input: {
        background: "rgba(15,23,42,0.8)",
        border: `1px solid ${COLORS.border}`,
        borderRadius: 4,
        color: COLORS.text,
        padding: "4px 6px",
        fontSize: 12,
        width: "100%",
        boxSizing: "border-box",
    },
};
