/**
 * Hidden World — static configuration.
 *
 * Compile-time constants only: mod ids, terrain generator parameters (ported
 * from `sandgenerator-web/js/configuration.js` "first step"), ghost palette
 * and the i18n key map. Runtime values live in `state.ts`.
 */

/** Mod id — used for item/sprite ids, storage namespace and i18n keys. */
import { MOD_ID } from "./ids.ts";
import type { GenerationParams, Rgba } from "./types.ts";

export const MOD = MOD_ID;

/** The custom hotbar item that toggles the ghost view. */
export const ITEM_ID = `${MOD}.lens`;
/** Sprite id for the item icon (generated by `tools/genIcon.ts`). */
export const ICON_SPRITE_ID = `${MOD}.lensIcon`;
/** Icon file inside the mod folder. */
export const ICON_PATH = "assets/lens.png";

/** Storage key holding the terrain seed (save-backed, one per save). */
export const STORAGE_KEY_SEED = "hiddenSeed";
/** Overlay id for the generation parameter picker (hotbar slot). */
export const OVERLAY_ID = `${MOD}.params`;
/** Fallback map size in cells when `api.grid.getDimensions` is unavailable. */
export const FALLBACK_CELLS = { width: 640, height: 360 };

// ----------------------------------------------------------------------------
// Terrain generator parameters — ported from sandgenerator-web "first step"
// (noiseGeneration1D "SkyLine" + noiseGeneration2D "Tunnel"/"Cave").
// Wave sets are "fix" typed in the web config; the tunables live in
// `GenerationParams` (percents, see `DEFAULT_PARAMS`).
// ----------------------------------------------------------------------------

/** Same fixed zoom the web generator applies to noise sample coordinates. */
export const NOISE_ZOOM_2D = 2;
export const NOISE_ZOOM_1D = 2;

/** Skyline globals (fix). */
export const SKYLINE_FIXED = { Phase: 0, Amp: 1 } as const;

/** Tunnel wave set (frequency/amplitude) — "fix" typed in the web config. */
export const TUNNEL_WAVES: readonly (readonly [number, number])[] = [
    [0.0075, 0.5],
    [0.015, 0.5],
    [0.05, 0.1],
    [0.09, 0.05],
];

/** Cave wave set (frequency/amplitude) — "fix" typed in the web config. */
export const CAVE_WAVES: readonly (readonly [number, number])[] = [
    [0.006, 0.5],
    [0.012, 0.5],
    [0.04, 0.1],
    [0.1, 0.02],
];

/** Default tunables — matching the user's chosen defaults. */
export const DEFAULT_PARAMS: GenerationParams = {
    sky: {
        bigWave: { periodCells: 1200, amplitudePercent: 15 },
        mediumWave: { periodCells: 800, amplitudePercent: 25 },
        lowWave: { periodCells: 400, amplitudePercent: 5 },
        roughness: { periodCells: 200, amplitudePercent: 3 },
    },
    baseHeightPercent: 55,
    tunnel: { thicknessPercent: 20, definitionPercent: 85, offsetX: 20, offsetY: -50 },
    cave: { thicknessPercent: 25, definitionPercent: 70, offsetX: 0, offsetY: -40 },
};

/**
 * Terrain codes stored in the hidden matrix (same ordering idea as
 * `sandgenerator-web/js/const.js` `itemsID_FIX`).
 */
export const TERRAIN = {
    SKY: 0,
    ROCK: 1,
    TUNNEL: 2,
    CAVE: 3,
} as const;

/**
 * What each matrix code paints in the ghost layer — a **terrain**, not an
 * image. Rock reads as **Stone** and caves as **Dirt**; sky and tunnels stay
 * `null`, i.e. transparent, so the carved corridors show as holes in the rock.
 * Colors come from
 * `doc/docs_tech/COLOR-CATALOG.md` § "Terrain metadata colors" (see below).
 */
export const CODE_TERRAIN: Record<number, string | null> = {
    [TERRAIN.SKY]: null,
    [TERRAIN.ROCK]: "stone",
    [TERRAIN.TUNNEL]: null,
    [TERRAIN.CAVE]: "dirt",
};

/** Matrix code → its short name (panel legend). */
export const CODE_LABELS: Record<number, string> = {
    [TERRAIN.SKY]: "sky",
    [TERRAIN.ROCK]: "rock",
    [TERRAIN.TUNNEL]: "tunnel",
    [TERRAIN.CAVE]: "cave",
};

/**
 * Terrain metadata colors — `doc/docs_tech/COLOR-CATALOG.md`,
 * § "Terrain metadata colors". These are the engine's own terrain `metaColor`s
 * (Stone `8421504`, Dirt `9593894`), used for the panel legend and as the
 * fallback when the engine lookup is unavailable.
 */
export const TERRAIN_META_COLORS: Record<string, string> = {
    stone: "#808080", // base stone terrain
    dirt: "#926426", // diggable terrain; can output sand
};

/** Fallback terrain display names (engine i18n is preferred when available). */
export const TERRAIN_META_NAMES: Record<string, string> = {
    stone: "Stone",
    dirt: "Dirt",
};

/** i18n namespace the engine uses for terrain names (`terrains|stone|name`). */
export const TERRAIN_NAME_KEY_PREFIX = "terrains";

/** Static colors per code (transparent where nothing is painted). RGBA 0–255.
 * These match `doc/docs_tech/COLOR-CATALOG.md`, § "Terrain metadata colors":
 * Rock (Stone) = #808080, Cave (Dirt) = #926426, Sky / Tunnels = transparent.
 */
export const FALLBACK_CODE_COLORS: Record<number, Rgba> = {
    [TERRAIN.SKY]: [0, 0, 0, 0],
    [TERRAIN.ROCK]: [0x80, 0x80, 0x80, 255], // Stone #808080
    [TERRAIN.TUNNEL]: [0, 0, 0, 0],
    [TERRAIN.CAVE]: [0x92, 0x64, 0x26, 255], // Dirt  #926426
};

/**
 * Ghost layer opacity over the normal map — configured as a percent because
 * the mod config UI only accepts integers; stored /100 in `runtime.alpha`.
 */
export const DEFAULT_GHOST_ALPHA_PERCENT = 45;
/** Config clamping bounds (percent). */
export const GHOST_ALPHA_PERCENT_MIN = 5;
export const GHOST_ALPHA_PERCENT_MAX = 100;

/** i18n keys, namespaced under `mods|hiddenword|…`. */
const NS = "mods|hiddenword";
export const KEY = {
    itemName: `${NS}|lens|name`,
    itemDesc: `${NS}|lens|desc`,
} as const;

/** Log prefix so every warning is attributable to this mod. */
export const LOG = "[hidden-word]";
