/**
 * GENERATED by `tools/gen-reference.ts` — do not edit.
 *
 * The api surface this mod uses, derived from the Phase 0 bundle index.
 * Register calls are typed from the definition interfaces the sdk ships;
 * everything else is listed with its arity and throw behaviour, and typed
 * `unknown`, because the bundle records the call and not a signature.
 *
 * Re-run `deno run -A tools/gen-reference.ts` after changing the mod.
 */

export namespace cooldown {
    /** arity 3; takes the engine context */
    export function check(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function isReady(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace drones {
    /** arity 6 */
    export function spawn(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
    ): unknown;
    /** arity 2 */
    export function kill(a0: unknown, a1: unknown): unknown;
}

export namespace sound {
    /** arity 3; takes the engine context */
    export function play(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function stop(a0: unknown, a1: unknown): unknown;
    /** arity 1; takes the engine context */
    export function stopAll(a0: unknown): unknown;
    /** arity 3; takes the engine context */
    export function playActive(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 1; takes the engine context */
    export function stopActive(a0: unknown): unknown;
    /** arity 3 */
    export function playLayers(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function calculateDistanceOptions(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
    ): unknown;
}

export namespace action {
    /** arity 1 */
    export function getActive(a0: unknown): unknown;
    /** arity 1 */
    export function getSelected(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function setCustomData(a0: unknown, a1: unknown): unknown;
}

export namespace workerLocal {
    /** arity 3; takes the engine context */
    export function getOrInit(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function set(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function get(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context */
    export function clear(a0: unknown, a1: unknown): unknown;
}

export namespace matters {
    /** arity 2; takes the engine context */
    export function register(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context; throws */
    export function getMatterTypeFromId(a0: unknown, a1: unknown): unknown;
    /** arity 7 */
    export function runSolidUpdate(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
        a6: unknown,
    ): unknown;
}

export namespace elements {
    /** arity 1; takes the engine context */
    export function getRegisteredTypes(a0: unknown): unknown;
    /** `id`: string; `nameKey`: string; `defaultDataFields`: { [key: string]: number }; `colors`: { variantFromDataField1?: { rangeMin?: number, rangeMax?: number, invert?: boolean, useGradient?: boolean, }, variants: [number, number, number][], }; `colors.variantFromDataField1`: { rangeMin?: number, rangeMax?: number, invert?: boolean, useGradient?: boolean,; `density`: number; `matterType`: MatterType; `isGrabbable`: boolean; `isTransportable`: boolean; `getExtraProps`: () => { data: Record<PropertyKey, any> } */
    export function register(
        definition: {
            id: string;
            nameKey: string;
            defaultDataFields: { [key: string]: number };
            colors: {
                variantFromDataField1?: {
                    rangeMin?: number;
                    rangeMax?: number;
                    invert?: boolean;
                    useGradient?: boolean;
                };
                variants: [number, number, number][];
            };
            density: number;
            matterType: unknown;
            isGrabbable: boolean;
            isTransportable: boolean;
            getExtraProps: unknown;
        },
    ): unknown;
    /** arity 3; takes the engine context */
    export function updateDefinition(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function addInteractionInfo(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context; throws */
    export function getElementTypeFromId(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context */
    export function getElementIdFromType(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context */
    export function getName(a0: unknown, a1: unknown): unknown;
    /** arity 4; takes the engine context */
    export function removeAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 4; takes the engine context */
    export function removeAtDeferred(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 5; takes the engine context */
    export function createAt(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 5; takes the engine context */
    export function replaceAt(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 3 */
    export function getElementTypeAtPos(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getResolvedTypeAtPos(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getMatterTypeAtPos(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function getResolvedTypeFromCellId(a0: unknown, a1: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getInfoAtPos(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function isTypeAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function isFreeFalling(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; takes the engine context */
    export function findFreePositionInStructure(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
    ): unknown;
    /** arity 5; takes the engine context */
    export function move(a0: unknown, a1: unknown, a2: unknown, a3: unknown, a4: unknown): unknown;
    /** arity 6; takes the engine context */
    export function moveAtSimulationIdle(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
    ): unknown;
    /** arity 5; takes the engine context */
    export function teleport(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 3; takes the engine context */
    export function getVelocity(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; takes the engine context */
    export function setVelocity(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 5; takes the engine context */
    export function addParticleVelocity(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 4; takes the engine context */
    export function convertToParticle(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function convertFromParticle(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 5; takes the engine context */
    export function swap(a0: unknown, a1: unknown, a2: unknown, a3: unknown, a4: unknown): unknown;
    /** arity 4; takes the engine context */
    export function getDataField(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 5; takes the engine context */
    export function setDataField(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 3 */
    export function getDataField1(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function setDataField1(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function getDataField2(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function setDataField2(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function getDataField3(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function setDataField3(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function getDataField4(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function setDataField4(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function refreshColorAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function markMovementBlocked(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function getConfig(a0: unknown): unknown;
    /** arity 4; takes the engine context */
    export function setPhysics(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 5; takes the engine context */
    export function setDuration(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
}

export namespace fire {
    /** arity 3 */
    export function canBurnElementAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function burnElementAt(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace world {
    /** arity 1; takes the engine context */
    export function getDimensions(a0: unknown): unknown;
    /** arity 3; takes the engine context */
    export function isCellEmpty(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function isTerrainAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2 */
    export function runWhenSimulationIdle(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function runAfterMutations(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context; throws */
    export function getCellTypeByName(a0: unknown, a1: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getCellId(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function setCellId(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function reportActivityToChunk(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 6 */
    export function excavate(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
    ): unknown;
    /** arity 3; takes the engine context */
    export function revealFogAtCell(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function redrawSurroundingCells(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
    ): unknown;
    /** arity 4; takes the engine context */
    export function createLightSource(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function removeLightSourcesAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 0 */
    export function markLightsDirty(): unknown;
    /** arity 4; takes the engine context */
    export function fadeLightSourceAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 6 */
    export function spawn(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
    ): unknown;
    /** arity 2 */
    export function destroy(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function pickUp(a0: unknown, a1: unknown): unknown;
    /** arity 1; takes the engine context */
    export function getAll(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function getById(a0: unknown, a1: unknown): unknown;
}

export namespace authorization {
    /** arity 3 */
    export function canGrab(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function canBuild(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function canUseTool(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function canUseToolAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function getZoneIdAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 1 */
    export function getPlayerZoneId(a0: unknown): unknown;
}

export namespace terrains {
    /** arity 1 */
    export function getConfig(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function getIdByType(a0: unknown, a1: unknown): unknown;
    /** `id`: string; `nameKey`: string; `hp`: number; `materialId`: number; `metaColor`: number; `colorHSL`: [number, number, number]; `excavationRequirements`: readonly string[]; `interactions`: readonly { kind: string; [key: string]: unknown }[]; `output`: { elementType: elements.ElementType; chance: number; }; `output.elementType`: elements.ElementType; `output.chance`: number */
    export function register(
        definition: {
            id: string;
            nameKey: string;
            hp: number;
            materialId: number;
            metaColor: number;
            colorHSL: [number, number, number];
            excavationRequirements: readonly string[];
            interactions: unknown;
            output: unknown;
        },
    ): unknown;
    /** arity 3; takes the engine context */
    export function updateDefinition(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 5 */
    export function createAt(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 5; takes the engine context */
    export function replaceAt(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 4; takes the engine context */
    export function removeAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function getGroundCellTypeAtPos(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function damageTerrain(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 4; takes the engine context */
    export function isPosTerrainId(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getTerrainData(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; takes the engine context */
    export function setTerrainHP(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function isPosTerrain(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 1 */
    export function isTerrain(a0: unknown): unknown;
    /** arity 4; takes the engine context */
    export function transform(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
}

export namespace wall {
    /** arity 1; takes the engine context */
    export function getPaletteData(a0: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getWallDataAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; takes the engine context */
    export function setWallDataAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 1; takes the engine context */
    export function getWallDataSize(a0: unknown): unknown;
}

export namespace shadows {
    /** arity 3 */
    export function refresh(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; takes the engine context */
    export function refreshRadius(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 6; takes the engine context */
    export function refreshRect(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
    ): unknown;
}

export namespace collector {
    /** arity 2 */
    export function getValueFromElementType(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context */
    export function getValueFromCellId(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function isCellCollectable(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context */
    export function isCellCollectableForSprite(a0: unknown, a1: unknown): unknown;
    /** arity 3; takes the engine context */
    export function notifyPickup(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace items {
    /** arity 0 */
    export function spriteMounts(): unknown;
    /** arity 1; takes the engine context */
    export function getRegisteredIds(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function register(a0: unknown, a1: unknown): unknown;
    /** arity 3; takes the engine context */
    export function updateDefinition(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function create(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function getActive(a0: unknown): unknown;
    /** arity 3 */
    export function isActive(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace projectiles {
    /** `id`: string; `sprite`: { id: string; tint?: number; }; `sprite.id`: string; `sprite.tint`: number; `getOptions`: () => Record<string, unknown>; `getModData`: (state: unknown, projectile: Projectile) => Record<string, unknown> */
    export function register(
        definition: {
            id: string;
            sprite: { id: string; tint?: number };
            getOptions: unknown;
            getModData: unknown;
        },
    ): unknown;
    /** arity 2; takes the engine context */
    export function createBlueprint(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function remove(a0: unknown, a1: unknown): unknown;
    /** arity 1; takes the engine context */
    export function getAll(a0: unknown): unknown;
    /** arity 5 */
    export function spawn(a0: unknown, a1: unknown, a2: unknown, a3: unknown, a4: unknown): unknown;
}

export namespace sprites {
    /** arity 4; takes the engine context */
    export function load(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 2; takes the engine context */
    export function get(a0: unknown, a1: unknown): unknown;
    /** arity 1; takes the engine context */
    export function hideAllPlayerModSprites(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function rotatePlayerModSprites(a0: unknown, a1: unknown): unknown;
}

export namespace reactions {
    /** arity 2 */
    export function registerContact(a0: unknown, a1: unknown): unknown;
}

export namespace excavation {
    /** arity 3 */
    export function registerProfile(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 11 */
    export function prepare(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
        a6: unknown,
        a7: unknown,
        a8: unknown,
        a9: unknown,
        a10: unknown,
    ): unknown;
}

export namespace processing {
    /** arity 2 */
    export function registerGrower(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function registerShaker(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function registerKineticPress(a0: unknown, a1: unknown): unknown;
}

export namespace conveyors {
    /** arity 3 */
    export function registerType(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace signals {
    /** arity 3; takes the engine context; throws */
    export function register(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace structures {
    /** arity 3 */
    export function getWeightedRecipe(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2 */
    export function selectWeightedOutput(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function register(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function isEnabledAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; throws */
    export function setEnabledAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function addProcessor(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; takes the engine context */
    export function updateDefinition(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function getAtCell(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function forEachOfType(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** `structureId`: StructureId; `fields`: PlacementConfigField[] */
    export function registerPlacementConfig(
        definition: { structureId: unknown; fields: unknown },
    ): unknown;
    /** arity 2 */
    export function isType(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function resolveTypeName(a0: unknown): unknown;
    /** arity 3 */
    export function hasBuiltAtCell(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function isTypeAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function update(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function updateMany(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function setData(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function setSpritesheetIndex(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function setSpritesheetIndexAt(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
    ): unknown;
    /** arity 2 */
    export function mapValueToSpritesheetIndex(a0: unknown, a1: unknown): unknown;
    /** arity 4 */
    export function setSpritesheetIndexByValue(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
    ): unknown;
    /** arity 5 */
    export function setSpritesheetIndexByValueAt(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 4 */
    export function build(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 4 */
    export function removeAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 4 */
    export function removeBetween(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function removeAtPositions(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 0 */
    export function beginBatchWrite(): unknown;
    /** arity 0 */
    export function endBatchWrite(): unknown;
    /** arity 3; takes the engine context */
    export function isBlockedByPlayer(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 1 */
    export function getConfig(a0: unknown): unknown;
    /** arity 1 */
    export function getUnlockedTypes(a0: unknown): unknown;
    /** arity 2 */
    export function isUnlocked(a0: unknown, a1: unknown): unknown;
    /** arity 4 */
    export function addVariant(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function isLauncherAt(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace launchers {
    /** arity 2; takes the engine context */
    export function registerType(a0: unknown, a1: unknown): unknown;
}

export namespace misc {
    /** arity 2; takes the engine context */
    export function register(a0: unknown, a1: unknown): unknown;
}

export namespace grid {
    /** arity 6 */
    export function iterateRect(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
    ): unknown;
    /** arity 5 */
    export function iterateCircle(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
}

export namespace energy {
    /** arity 4; takes the engine context */
    export function registerType(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 5 */
    export function add(a0: unknown, a1: unknown, a2: unknown, a3: unknown, a4: unknown): unknown;
    /** arity 3 */
    export function addBatch(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getNetwork(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getNetworkFreeCapacity(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; takes the engine context */
    export function consumeExcludingNetwork(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
    ): unknown;
    /** arity 3 */
    export function consume(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace raycast {
    /** arity 5; takes the engine context */
    export function cast(a0: unknown, a1: unknown, a2: unknown, a3: unknown, a4: unknown): unknown;
}

export namespace effects {
    /** arity 4; takes the engine context */
    export function createDistortionWave(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
    ): unknown;
    /** arity 6; takes the engine context */
    export function createLaser(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
    ): unknown;
    /** arity 4 */
    export function createLight(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 2 */
    export function removeLight(a0: unknown, a1: unknown): unknown;
    /** arity 4 */
    export function createParticles(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 5 */
    export function createEffect(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
}

export namespace schedule {
    /** arity 2 */
    export function nextTick(a0: unknown, a1: unknown): unknown;
}

export namespace queue {
    /** arity 2 */
    export function registerHandler(a0: unknown, a1: unknown): unknown;
    /** arity 5; takes the engine context */
    export function enqueue(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 5; takes the engine context */
    export function enqueueInTicks(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
    ): unknown;
    /** arity 4 */
    export function enqueueSkipTick(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 2; takes the engine context */
    export function removeByKey(a0: unknown, a1: unknown): unknown;
    /** arity 1; takes the engine context */
    export function process(a0: unknown): unknown;
}

export namespace ui {
    /** arity 3 */
    export function update(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 1; takes the engine context */
    export function openPauseMenu(a0: unknown): unknown;
    /** arity 2 */
    export function showTooltip(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function toast(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function alert(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function confirm(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 6; takes the engine context */
    export function prompt(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
    ): unknown;
    /** arity 3; takes the engine context */
    export function select(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function mount(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function setVisible(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2 */
    export function useRefresh(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function useScale(a0: unknown): unknown;
    /** arity 3 */
    export function useGameEvent(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function register(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function unregister(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace debug {
    /** arity 3; takes the engine context */
    export function register(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace patterns {
    /** arity 1 */
    export function createCircle(a0: unknown): unknown;
    /** arity 8 */
    export function excavate(
        a0: unknown,
        a1: unknown,
        a2: unknown,
        a3: unknown,
        a4: unknown,
        a5: unknown,
        a6: unknown,
        a7: unknown,
    ): unknown;
}

export namespace workers {
    /** arity 1; throws */
    export function getIdByName(a0: unknown): unknown;
    /** arity 3 */
    export function postToEachThreadColumnSequentiallyAwait(
        a0: unknown,
        a1: unknown,
        a2: unknown,
    ): unknown;
    /** arity 3 */
    export function register(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context; throws */
    export function create(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function get(a0: unknown, a1: unknown): unknown;
}

export namespace triggers {
    /** `interval`: number; `callback`: () => void */
    export function register(definition: { interval: number; callback: unknown }): unknown;
}

export namespace random {
    /** arity 2 */
    export function int(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function float(a0: unknown, a1: unknown): unknown;
}

export namespace resources {
    /** arity 3 */
    export function collectFluxiteAtCell(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2 */
    export function refresh(a0: unknown, a1: unknown): unknown;
    /** arity 3; takes the engine context */
    export function updateEnergy(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace factory {
    /** arity 1 */
    export function getLevel(a0: unknown): unknown;
    /** arity 2 */
    export function flushDeferredLevelUps(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function canUnlockNextTier(a0: unknown): unknown;
    /** arity 1 */
    export function unlockNextTier(a0: unknown): unknown;
    /** arity 2 */
    export function addViabilityGold(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function getProcessCount(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function getProcessRate(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function recordProcess(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function ensureProcessAtLeast(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace tech {
    /** arity 1 */
    export function getDefinition(a0: unknown): unknown;
    /** arity 2 */
    export function updateDefinition(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function addDefinition(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function appendUnlock(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function registerNode(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function isResearched(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function isLocked(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function setLocked(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace rendering {
    /** arity 3 */
    export function getDrawPos(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function getCellDrawPos(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 0 */
    export function getGridMetrics(): unknown;
    /** arity 1; takes the engine context */
    export function getOverlayViewportSize(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function withOverlayContext(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context */
    export function stepVideoZoom(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function register(a0: unknown): unknown;
    /** arity 3; takes the engine context */
    export function warmup(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace building {
    /** arity 2 */
    export function getSnappedCellPosition(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function isBlockedByTerrainOrElements(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 1 */
    export function cancelPlacement(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function selectStructure(a0: unknown, a1: unknown): unknown;
}

export namespace storage {
    /** arity 2; takes the engine context */
    export function ensure(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function get(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function set(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3 */
    export function remove(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace input {
    /** arity 4; takes the engine context */
    export function registerKeyBinding(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 1; takes the engine context */
    export function getMouseCellPosition(a0: unknown): unknown;
    /** arity 1; takes the engine context */
    export function getMouseWorldPosition(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function getBoundKeys(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function getDisplayKey(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2 */
    export function triggerBinding(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function pressBinding(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function releaseBinding(a0: unknown, a1: unknown): unknown;
    /** arity 1; takes the engine context */
    export function resetMouseState(a0: unknown): unknown;
    /** arity 1; takes the engine context */
    export function isCtrlHeld(a0: unknown): unknown;
    /** arity 1; takes the engine context */
    export function isAltHeld(a0: unknown): unknown;
}

export namespace player {
    /** arity 1; takes the engine context */
    export function getPosition(a0: unknown): unknown;
    /** arity 3; takes the engine context */
    export function setPosition(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function setVelocity(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function setMovementSpeedMultiplier(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function setMovementMode(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function isOnGround(a0: unknown): unknown;
    /** arity 1 */
    export function teleportToGround(a0: unknown): unknown;
    /** arity 2; takes the engine context */
    export function has(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context; throws */
    export function add(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context */
    export function remove(a0: unknown, a1: unknown): unknown;
    /** arity 3 */
    export function isCollidingWithCell(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4 */
    export function isWithinRadius(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function isPositionClear(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace camera {
    /** arity 1 */
    export function snapToPlayer(a0: unknown): unknown;
    /** arity 3 */
    export function setFocusAtWorld(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2; takes the engine context */
    export function releaseFocusToPlayer(a0: unknown, a1: unknown): unknown;
}

export namespace scene {
    /** arity 1; takes the engine context */
    export function getActive(a0: unknown): unknown;
}

export namespace maps {
    /** arity 1; takes the engine context */
    export function getArtifactLocations(a0: unknown): unknown;
    /** arity 1; takes the engine context */
    export function getActive(a0: unknown): unknown;
    /** arity 0 */
    export function getAvailable(): unknown;
    /** arity 2; takes the engine context */
    export function start(a0: unknown, a1: unknown): unknown;
}

export namespace pipes {
    /** arity 3 */
    export function isAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function isEnabledAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3 */
    export function getConnectedVentsAt(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 4; throws */
    export function setEnabledAt(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
}

export namespace game {
    /** arity 2; takes the engine context */
    export function start(a0: unknown, a1: unknown): unknown;
    /** arity 3; takes the engine context */
    export function save(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 2 */
    export function load(a0: unknown, a1: unknown): unknown;
}

export namespace progression {
    /** arity 2 */
    export function complete(a0: unknown, a1: unknown): unknown;
}

export namespace upgrades {
    /** `id`: string; `nameKey`: string */
    export function registerCategory(definition: { id: string; nameKey: string }): unknown;
    /** `itemId`: string; `itemNameKey`: string; `categoryId`: string; `upgrade`: { id: string; nameKey?: string; descriptionKey?: string; maxLevel: number; costs: number[]; oneOff?: boolean; }; `upgrade.id`: string; `upgrade.nameKey`: string; `upgrade.descriptionKey`: string; `upgrade.maxLevel`: number; `upgrade.costs`: number[]; `upgrade.oneOff`: boolean */
    export function register(
        definition: {
            itemId: string;
            itemNameKey: string;
            categoryId: string;
            upgrade: {
                id: string;
                nameKey?: string;
                descriptionKey?: string;
                maxLevel: number;
                costs: number[];
                oneOff?: boolean;
            };
        },
    ): unknown;
    /** arity 4; takes the engine context */
    export function updateDefinition(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 4; takes the engine context */
    export function setLevel(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getLevel(a0: unknown, a1: unknown, a2: unknown): unknown;
    /** arity 3; takes the engine context */
    export function getAvailableLevel(a0: unknown, a1: unknown, a2: unknown): unknown;
}

export namespace tools {
    /** arity 2; takes the engine context; throws */
    export function setGrabberSize(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function getGrabberSize(a0: unknown): unknown;
    /** arity 1 */
    export function isGrabberActive(a0: unknown): unknown;
}

export namespace teleportZones {
    /** arity 4; takes the engine context */
    export function teleportPlayerTo(a0: unknown, a1: unknown, a2: unknown, a3: unknown): unknown;
}

export namespace i18n {
    /** arity 2 */
    export function t(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function register(a0: unknown, a1: unknown): unknown;
    /** arity 0 */
    export function getLocale(): unknown;
    /** arity 2 */
    export function hasTranslation(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function setLocale(a0: unknown): unknown;
    /** arity 0 */
    export function getLanguages(): unknown;
    /** arity 2 */
    export function formatNumber(a0: unknown, a1: unknown): unknown;
    /** arity 0 */
    export function getAvailableLocales(): unknown;
    /** arity 1 */
    export function key(a0: unknown): unknown;
    /** arity 1 */
    export function getName(a0: unknown): unknown;
    /** arity 1 */
    export function getDescription(a0: unknown): unknown;
    /** arity 2 */
    export function translatable(a0: unknown, a1: unknown): unknown;
    /** arity 2 */
    export function setGlobal(a0: unknown, a1: unknown): unknown;
    /** arity 1 */
    export function getGlobal(a0: unknown): unknown;
    /** arity 1 */
    export function clearGlobal(a0: unknown): unknown;
    /** arity 0 */
    export function getGlobals(): unknown;
    /** arity 1 */
    export function formatKeyForDisplay(a0: unknown): unknown;
    /** arity 1 */
    export function syncKeyBindings(a0: unknown): unknown;
}

export namespace config {
    /** arity 0 */
    export function config(): unknown;
}

export namespace discoveries {
    /** arity 2; takes the engine context */
    export function addElement(a0: unknown, a1: unknown): unknown;
    /** arity 2; takes the engine context */
    export function addTerrain(a0: unknown, a1: unknown): unknown;
}

export namespace extend {
    /** arity 3 */
    export function extend(a0: unknown, a1: unknown, a2: unknown): unknown;
}

// 337 members
