import type { StyleObj } from "./types.ts";

export const COLORS = {
    bg: "rgba(8, 10, 16, 0.94)",
    bgRaised: "rgba(16, 20, 30, 0.96)",
    border: "#2a3548",
    borderSoft: "#1e2736",
    accent: "#ffe700",
    accentDim: "#b8a400",
    text: "#d4dce8",
    dim: "#6e7a8c",
    muted: "#4a5568",
    good: "#5ddea0",
    warn: "#f0a060",
    danger: "#ff6b7a",
    tabActive: "#1a2740",
    rowHover: "rgba(255, 231, 0, 0.04)",
    bar: "#3d5a80",
    barFill: "#ffe700",
};

export const styles: Record<string, StyleObj> = {
    root: {
        position: "fixed",
        left: "50%",
        top: "50%",
        transform: "translate(-50%, -50%)",
        width: "560px",
        maxWidth: "94vw",
        maxHeight: "82vh",
        display: "flex",
        flexDirection: "column",
        background: COLORS.bg,
        border: `1px solid ${COLORS.border}`,
        borderRadius: "12px",
        color: COLORS.text,
        font: "12px/1.45 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
        boxShadow: "0 16px 48px rgba(0,0,0,0.65), 0 0 0 1px rgba(255,231,0,0.06)",
        zIndex: 9500,
        overflow: "hidden",
        backdropFilter: "blur(8px)",
    },
    header: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "10px 14px",
        borderBottom: `1px solid ${COLORS.border}`,
        background: "linear-gradient(180deg, rgba(30,36,50,0.9), rgba(12,14,22,0.5))",
        flexShrink: 0,
    },
    title: {
        flex: 1,
        color: COLORS.accent,
        letterSpacing: "0.08em",
        fontWeight: 600,
        fontSize: "13px",
        textTransform: "uppercase",
    },
    tabs: {
        display: "flex",
        gap: "2px",
        padding: "6px 10px 0",
        borderBottom: `1px solid ${COLORS.borderSoft}`,
        flexShrink: 0,
        background: COLORS.bgRaised,
    },
    tab: {
        background: "transparent",
        color: COLORS.dim,
        border: "none",
        borderBottom: "2px solid transparent",
        borderRadius: "6px 6px 0 0",
        padding: "8px 14px",
        cursor: "pointer",
        font: "inherit",
        letterSpacing: "0.04em",
        transition: "color 0.12s, border-color 0.12s, background 0.12s",
    },
    tabActive: {
        background: COLORS.tabActive,
        color: COLORS.accent,
        border: "none",
        borderBottom: `2px solid ${COLORS.accent}`,
        borderRadius: "6px 6px 0 0",
        padding: "8px 14px",
        cursor: "pointer",
        font: "inherit",
        letterSpacing: "0.04em",
        fontWeight: 600,
    },
    toolbar: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "8px 12px",
        borderBottom: `1px solid ${COLORS.borderSoft}`,
        flexShrink: 0,
        flexWrap: "wrap",
    },
    button: {
        background: "#1a2230",
        color: COLORS.text,
        border: `1px solid ${COLORS.border}`,
        borderRadius: "6px",
        padding: "5px 12px",
        cursor: "pointer",
        font: "inherit",
        letterSpacing: "0.03em",
    },
    buttonPrimary: {
        background: "linear-gradient(180deg, #3a3410, #2a2408)",
        color: COLORS.accent,
        border: `1px solid ${COLORS.accentDim}`,
        borderRadius: "6px",
        padding: "5px 14px",
        cursor: "pointer",
        font: "inherit",
        fontWeight: 600,
        letterSpacing: "0.04em",
    },
    buttonDisabled: {
        background: "#141820",
        color: COLORS.muted,
        border: `1px solid ${COLORS.borderSoft}`,
        borderRadius: "6px",
        padding: "5px 14px",
        cursor: "default",
        font: "inherit",
        opacity: 0.7,
    },
    input: {
        flex: 1,
        minWidth: "120px",
        background: "#0c1018",
        color: COLORS.text,
        border: `1px solid ${COLORS.border}`,
        borderRadius: "6px",
        padding: "5px 10px",
        font: "inherit",
        outline: "none",
    },
    select: {
        background: "#0c1018",
        color: COLORS.text,
        border: `1px solid ${COLORS.border}`,
        borderRadius: "6px",
        padding: "5px 8px",
        font: "inherit",
        cursor: "pointer",
    },
    body: {
        flex: 1,
        overflowY: "auto",
        padding: "8px 10px",
        minHeight: "200px",
    },
    homeWrap: {
        display: "flex",
        flexDirection: "column",
        gap: "14px",
        padding: "4px 0",
    },
    homeGrid: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "10px",
        padding: "2px 4px",
    },
    groupSection: {
        padding: "0 4px 4px",
    },
    groupTitle: {
        color: COLORS.dim,
        fontSize: "10px",
        letterSpacing: "0.12em",
        textTransform: "uppercase",
        marginBottom: "8px",
    },
    groupGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))",
        gap: "10px",
    },
    groupCard: {
        background: COLORS.bgRaised,
        border: `1px solid ${COLORS.border}`,
        borderRadius: "10px",
        padding: "12px 14px",
        display: "flex",
        flexDirection: "column",
        gap: "4px",
    },
    card: {
        background: COLORS.bgRaised,
        border: `1px solid ${COLORS.border}`,
        borderRadius: "10px",
        padding: "14px 16px",
        display: "flex",
        flexDirection: "column",
        gap: "4px",
    },
    cardLabel: {
        color: COLORS.dim,
        fontSize: "10px",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
    },
    cardValue: {
        color: COLORS.accent,
        fontSize: "22px",
        fontWeight: 700,
        letterSpacing: "0.02em",
    },
    cardSub: {
        color: COLORS.dim,
        fontSize: "11px",
    },
    list: {
        display: "flex",
        flexDirection: "column",
        gap: "2px",
    },
    row: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "6px 8px",
        borderRadius: "6px",
        borderBottom: `1px solid ${COLORS.borderSoft}`,
    },
    swatch: {
        width: "10px",
        height: "10px",
        borderRadius: "2px",
        flexShrink: 0,
        border: "1px solid rgba(255,255,255,0.12)",
    },
    grow: {
        flex: 1,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    count: {
        color: COLORS.accent,
        fontWeight: 700,
        fontVariantNumeric: "tabular-nums",
        minWidth: "52px",
        textAlign: "right",
    },
    barTrack: {
        width: "64px",
        height: "4px",
        borderRadius: "2px",
        background: COLORS.bar,
        overflow: "hidden",
        flexShrink: 0,
    },
    barFill: {
        height: "100%",
        background: `linear-gradient(90deg, ${COLORS.accentDim}, ${COLORS.barFill})`,
        borderRadius: "2px",
    },
    footer: {
        padding: "7px 14px",
        color: COLORS.dim,
        borderTop: `1px solid ${COLORS.border}`,
        fontSize: "11px",
        display: "flex",
        justifyContent: "space-between",
        flexShrink: 0,
        background: "rgba(0,0,0,0.25)",
    },
    empty: {
        padding: "32px 16px",
        textAlign: "center",
        color: COLORS.dim,
    },
    spinner: {
        color: COLORS.accent,
        letterSpacing: "0.06em",
    },

    itemList: {
        display: "flex",
        flexDirection: "column",
        gap: "3px",
        marginTop: "8px",
        paddingTop: "8px",
        borderTop: "1px solid #1e2736",
    },
    itemRow: {
        display: "flex",
        alignItems: "center",
        gap: "6px",
        fontSize: "11px",
        color: "#6e7a8c",
    },
    itemRowPrimary: {
        display: "flex",
        alignItems: "center",
        gap: "6px",
        fontSize: "12px",
        color: "#d4dce8",
        fontWeight: 600,
    },
    editor: {
        display: "flex",
        flexDirection: "column",
        gap: "10px",
        padding: "4px",
    },
    editorBar: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        flexWrap: "wrap",
        paddingBottom: "8px",
        borderBottom: "1px solid #2a3548",
    },
    editorList: {
        display: "flex",
        flexDirection: "column",
        gap: "8px",
    },
    editorCard: {
        background: "rgba(16, 20, 30, 0.96)",
        border: "1px solid #2a3548",
        borderRadius: "8px",
        overflow: "hidden",
    },
    editorCardHead: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "8px 10px",
        cursor: "pointer",
        background: "rgba(30,36,50,0.5)",
    },
    editorCardBody: {
        padding: "10px 12px 12px",
        borderTop: "1px solid #1e2736",
        display: "flex",
        flexDirection: "column",
        gap: "6px",
    },
    fieldLabel: {
        color: "#6e7a8c",
        fontSize: "10px",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
    },
    addRow: {
        display: "flex",
        gap: "6px",
        alignItems: "center",
        marginTop: "6px",
        flexWrap: "wrap",
    },
    dangerBtn: {
        background: "#2a1520",
        color: "#ff6b7a",
        border: "1px solid #ff6b7a",
        borderRadius: "5px",
        padding: "2px 8px",
        cursor: "pointer",
        font: "inherit",
    },

};
